
server:
  port: 8763

spring:
  application:
    name: yp_gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: YP_RESTAURANT
        uri: http://yprestaurant.mybluemix.net
        predicates:
        - Path=/rest/**
        filters:
        - StripPrefix=1
      - id: YP_SKIRESORT
        uri: http://ypskiresort.mybluemix.net
        predicates:
        - Path=/ski/**
        filters:
        - StripPrefix=1
      - id: YP_MUSEUM
        uri: http://ypmuseum.mybluemix.net
        predicates:
        - Path=/museum/**
        filters:
        - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://ypserver.mybluemix.net/eureka
  instance:
    hostname: localhost
    metadataMap:
      instanceId: yp_gateway


---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80