server:
  port: 8763

spring:
  application:
    name: yp_gateway

eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://ypserver.mybluemix.net/eureka
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 3
    lease-renewal-interval-in-seconds: 1
    metadataMap:
      instanceId: yp_gateway
zuul:
  routes:
    api-restaurant:
      path: /rest/**
      url: http://yprestaurant.mybluemix.net
    api-skiresort:
      path: /ski/**
      url: http://ypskiresort.mybluemix.net
    api-museum:
      path: /museum/**
      url: http://ypmuseum.mybluemix.net
    api-company:
      path: /company/**
      url: http://ypcompany.mybluemix.net


---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80